# Generated by Django 4.0 on 2022-04-22 17:50

import django.core.validators
from django.db import migrations, models
import expenses_tracker.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expenses_tracker.profiles.validators.username_isalpha_validator])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expenses_tracker.profiles.validators.username_isalpha_validator])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_picture', models.ImageField(blank=True, default='images/profile-pictures/default/user.png', upload_to='images/profile-pictures/', validators=[expenses_tracker.profiles.validators.image_max_size_validator])),
            ],
        ),
    ]
